# Generated by Django 4.0.1 on 2022-07-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='shor',
            new_name='short',
        ),
        migrations.AddField(
            model_name='urls',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
