# Generated by Django 4.0.1 on 2022-07-11 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorturl', '0002_rename_shor_urls_short_urls_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
